imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] }
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    trusted_proxies: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - '::fields.html.twig'
    globals:
        images_path: %coastersworldPathImages%
        coastersworldAdminEmailAddress: %coastersworldAdminEmailAddress%
        coastersworldPasswordChangeTime: %coastersworldPasswordChangeTime%

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: login
    disable_delivery: false

# Knp Paginator Configuration
knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

# LiipImagineBundle
liip_imagine:
    resolvers:
       default:
            web_path:
                cache_prefix: cache
    driver : imagick
    filter_sets:
        article:
            quality: 80
            filters:
                thumbnail: { size: [840, 280], mode: outbound }
                # watermark:
                    # image: Resources/public/images/watermark.png
                    # size: 0.25
                    # position: topleft
        thumb_article:
            quality: 50
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
        thumb_image:
            quality: 80
            filters:
                thumbnail: { size: [250, 250], mode: outbound }
