coasters_world_core:
    resource: "@CoastersWorldCoreBundle/Resources/config/routing.yml"

coasters_world_user:
    resource: "@CoastersWorldUserBundle/Resources/config/routing.yml"
    prefix:   /user

coasters_world_news:
    resource: "@CoastersWorldNewsBundle/Resources/config/routing.yml"
    prefix:   /news

login:
    pattern:   /login
    defaults:  { _controller: CoastersWorldUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
