coasters_world_site:
    resource: "@CoastersWorldSiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: CoastersWorldSiteBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
