coasters_world_site:
    resource: "@CoastersWorldSiteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: CoastersWorldSiteBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

register:
    pattern:  /inscription
    defaults: { _controller: CoastersWorldSiteBundle:Security:register }

mot_de_passe_oublie:
    pattern:  /mot-de-passe-oublie
    defaults: { _controller: CoastersWorldSiteBundle:Security:motdepasseOublie }

_imagine:
    resource: .
    type:     imagine
