security:
    encoders:
        CoastersWorld\Bundle\UserBundle\Entity\User:
            algorithm:        sha512

        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: CoastersWorldUserBundle:User, property: username }

        in_memory:
            memory:
                users:
                    florian:  { password: test, roles: [ 'ROLE_USER' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/*
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /news/list
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/news/new, roles: ROLE_ADMIN }
