coasters_world_database_index:
    pattern:  /
    defaults: { _controller: CoastersWorldDatabaseBundle:Coaster:index }

coasters_world_database_view:
    pattern:  /view/{slug}
    defaults: { _controller: CoastersWorldDatabaseBundle:Coaster:view }

coasters_world_database_search_ajax:
    pattern:  /search
    defaults: { _controller: CoastersWorldDatabaseBundle:Coaster:searchAjax }
