parameters:
#    coasters_world_news.example.class: CoastersWorld\Bundle\NewsBundle\Example

services:
#    coasters_world_news.example:
#        class: %coasters_world_news.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
