coasters_world_core_homepage:
    pattern:  /
    defaults: { _controller: CoastersWorldSiteBundle:Default:index }

coasters_world_database_index:
    pattern:  /coaster
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:index }

coasters_world_database_view:
    pattern:  /coaster/view/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:view }

coasters_world_database_search_ajax:
    pattern:  /coaster/search
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:searchAjax }

coasters_world_news_list:
    pattern:  /news/list/{page}
    defaults: { _controller: CoastersWorldSiteBundle:News:list, page: 1 }
    requirements:
        page: \d+

coasters_world_news_view:
    pattern:  /news/view/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:News:view }

coasters_world_news_new:
    pattern:  /news/new
    defaults: { _controller: CoastersWorldSiteBundle:News:edit }

coasters_world_news_edit:
    pattern:  /news/edit/{id}
    defaults: { _controller: CoastersWorldSiteBundle:News:edit }

coasters_world_news_comment_create:
    pattern:  /news/comment/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Comment:create }
    requirements:
        _method:  POST
        id: \d+

coasters_world_image_upload:
    pattern:  /upload
    defaults: { _controller: CoastersWorldSiteBundle:Image:upload }

coasters_world_image_test:
    pattern:  /test
    defaults: { _controller: CoastersWorldSiteBundle:Image:test }
