######## Homepage
coasters_world_homepage:
    pattern:  /
    defaults: { _controller: CoastersWorldSiteBundle:Article:list, page: 1 }

######## BDD
coasters_world_database_index:
    pattern:  /coaster
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:index }

database_search_ajax:
    pattern:  /coaster/search
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:searchAjax }

coasters_world_database_rating_new:
    pattern:  /coaster/rating/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Rating:new }
    requirements:
        _method:  POST

feedback_create:
    pattern:  /coaster/comment/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Feedback:create }
    requirements:
        _method:  POST
        id: \d+

coasters_world_database_view:
    pattern:  /coaster/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:view }
    requirements:
        slug: "[a-z0-9\-§]+"

######## User
coasters_world_register_succeed:
    pattern:  /inscription/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:registerSucceed }

coasters_world_activate:
    pattern:   /activation/{userid}-{key}
    defaults:  { _controller: CoastersWorldSiteBundle:Security:activate }
    requirements:
        userid: \d+
        key: "[a-z0-9]+"

coasters_world_activate_succeed:
    pattern:  /activation/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:activateSucceed }

coasters_world_change_password:
    pattern:   /changement-mot-de-passe/{userid}-{key}
    defaults:  { _controller: CoastersWorldSiteBundle:Security:changePassword }
    requirements:
        userid: \d+
        key: "[a-z0-9]+"

coasters_world_change_password_succeed:
    pattern:  /changement-mot-de-passe/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:changePasswordSucceed }

######## Article
# Redirection de la première page des news vers la page d'accueil du site
cw_article_list_first_page:
    pattern: /news
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: coasters_world_homepage
        permanent: false

cw_article_list_first_page_duplicate:
    pattern: /news/page/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: coasters_world_homepage
        permanent: false

# Liste des articles
cw_article_list:
    pattern:  /news/page/{page}
    defaults: { _controller: CoastersWorldSiteBundle:Article:list, page: 1 }
    requirements:
        page: \d+

# Création d'un article
cw_article_new:
    pattern:  /news/new
    defaults: { _controller: CoastersWorldSiteBundle:Article:edit }

# Modification d'un article
cw_article_edit:
    pattern:  /news/edit/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Article:edit }

# Suppression d'un article
cw_article_remove:
    pattern:  /news/remove/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Article:remove }

# Création d'un commentaire
cw_article_comment_create:
    pattern:  /news/comment/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Comment:create }
    requirements:
        _method:  POST
        id: \d+

# Conversion markdown to html
cw_article_md_to_html_ajax:
    pattern:  /news/convert-markdown
    defaults: { _controller: CoastersWorldSiteBundle:Article:convertMarkdown }
    requirements:
        _method:  POST

# Recherche d'articles (ajax)
cw_article_search_ajax:
    pattern: /news/search
    defaults: { _controller: CoastersWorldSiteBundle:Article:search }
    requirements:
        _method:  POST

cw_article_tag_first_page:
    pattern:  /news/tag/{slug}/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Article:listTag }
    requirements:
        slug: "[a-zA-Z0-9\-§]+"
        id: "\d+"

cw_article_tag:
    pattern:  /news/tag/{slug}/{id}/page/{page}
    defaults: { _controller: CoastersWorldSiteBundle:Article:listTag, page: 1 }
    requirements:
        slug: "[a-zA-Z0-9\-§]+"
        id: "\d+"
        page: "\d+"

# Affichage d'un article
cw_article_view:
    pattern:  /news/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Article:view }
    requirements:
        slug: "[a-z0-9\-§]+"

######## Image
coasters_world_image_upload:
    pattern:  /image/upload
    defaults: { _controller: CoastersWorldSiteBundle:Image:upload }

coasters_world_image_list:
    pattern:  /image/list
    defaults: { _controller: CoastersWorldSiteBundle:Image:list }

coasters_world_image_edit:
    pattern:  /image/edit/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Image:edit }
    requirements:
        id: \d+

cw_image_search_ajax:
    pattern:  /image/search
    defaults: { _controller: CoastersWorldSiteBundle:Image:searchAjax }
    requirements:
        id: \d+

######## Counter
counter_list:
    pattern: /coaster/list/{page}
    defaults: { _controller: CoastersWorldSiteBundle:Counter:list, page: 1 }

counter_add:
    pattern: /coaster/add/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Counter:add }
