######## Homepage
coasters_world_homepage:
    pattern:  /
    defaults: { _controller: CoastersWorldSiteBundle:News:list, page: 1 }

######## BDD
coasters_world_database_index:
    pattern:  /coaster
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:index }

database_search_ajax:
    pattern:  /coaster/search
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:searchAjax }

coasters_world_database_rating_new:
    pattern:  /coaster/rating/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Rating:new }
    requirements:
        _method:  POST

coaster_comment_create:
    pattern:  /coaster/comment/{id}
    defaults: { _controller: CoastersWorldSiteBundle:CoasterComment:create }
    requirements:
        _method:  POST
        id: \d+

coasters_world_database_view:
    pattern:  /coaster/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:Coaster:view }
    requirements:
        slug: "[a-z0-9\-]+"

######## User

coasters_world_register_succeed:
    pattern:  /inscription/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:registerSucceed }

coasters_world_activate:
    pattern:   /activation/{userid}-{key}
    defaults:  { _controller: CoastersWorldSiteBundle:Security:activate }
    requirements:
        userid: \d+
        key: "[a-z0-9]+"

coasters_world_activate_succeed:
    pattern:  /activation/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:activateSucceed }

coasters_world_change_password:
    pattern:   /changement-mot-de-passe/{userid}-{key}
    defaults:  { _controller: CoastersWorldSiteBundle:Security:changePassword }
    requirements:
        userid: \d+
        key: "[a-z0-9]+"

coasters_world_change_password_succeed:
    pattern:  /changement-mot-de-passe/succes
    defaults: { _controller: CoastersWorldSiteBundle:Security:changePasswordSucceed }

######## News

# Redirection de la première page des news vers la page d'accueil du site
coasters_world_news_list_first_page:
    pattern: /news
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: coasters_world_homepage
        permanent: false

coasters_world_news_list_first_page_duplicate:
    pattern: /news/page/1
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: coasters_world_homepage
        permanent: false

# Liste des news
coasters_world_news_list:
    pattern:  /news/page/{page}
    defaults: { _controller: CoastersWorldSiteBundle:News:list, page: 1 }
    requirements:
        page: \d+

# Création d'une news
coasters_world_news_new:
    pattern:  /news/new
    defaults: { _controller: CoastersWorldSiteBundle:News:edit }

# Modification d'une news
coasters_world_news_edit:
    pattern:  /news/edit/{id}
    defaults: { _controller: CoastersWorldSiteBundle:News:edit }

# Création d'un commentaire
coasters_world_news_comment_create:
    pattern:  /news/comment/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Comment:create }
    requirements:
        _method:  POST
        id: \d+

# Affichage d'une news
coasters_world_news_view:
    pattern:  /news/{slug}
    defaults: { _controller: CoastersWorldSiteBundle:News:view }
    requirements:
        slug: "[a-z0-9\-]+"

######## Image
coasters_world_image_upload:
    pattern:  /image/upload
    defaults: { _controller: CoastersWorldSiteBundle:Image:upload }

coasters_world_image_list:
    pattern:  /image/list
    defaults: { _controller: CoastersWorldSiteBundle:Image:list }

coasters_world_image_edit:
    pattern:  /image/edit/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Image:edit }
    requirements:
        id: \d+

######## Counter
counter_list:
    pattern: /coaster/list/{page}
    defaults: { _controller: CoastersWorldSiteBundle:Counter:list, page: 1 }

counter_add:
    pattern: /coaster/add/{id}
    defaults: { _controller: CoastersWorldSiteBundle:Counter:add }
