parameters:
#    coasters_world_site.example.class: CoastersWorld\Bundle\SiteBundle\Example

services:
#    coasters_world_site.example:
#        class: %coasters_world_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
