parameters:
   coasters_world_news.form.news_type.class: CoastersWorld\Bundle\SiteBundle\Form\Type\NewsType

services:
    coasters_world_news.form.news_type:
       class: %coasters_world_news.form.news_type.class%
       tags:
            - { name: form.type, alias: news_type }
