CoastersWorld\Bundle\SiteBundle\Entity\Image:
    properties:
        file:
            - File:
                maxSize: 6000000

CoastersWorld\Bundle\SiteBundle\Entity\User:
    properties:
        username:
            - NotBlank:
                message: "Veuillez renseigner un identifiant."
            - Length:
                min: 3
                max: 32
                minMessage: "Votre identifiant doit contenir au moins {{ limit }} caractères."
                maxMessage: "Votre identifiant doit contenir moins de {{ limit }} caractères."
        email:
            - Email:
                message: "{{ value }} n'est pas une adresse e-mail valide."
            - Length:
                max: 255
                maxMessage: "Votre adresse e-mail ne peut pas contenir plus de {{ limit }} caractères."
        password:
            - NotBlank:
                message : "Veuillez choisir un mot de passe."
            - Length:
                min: 6
                max: 20
                minMessage: "Votre mot de passe doit contenir au minimum {{ limit }} caractères."
                maxMessage: "Votre mot de passe doit contenir au maximum {{ limit }} caractères."
